### ISSUE TITLE
Измененный порядок выбора пабликов?

### ISSUE THREAD

**Issue by sandman595** [nechepurenkoN/spbetu2020_summer_practice#7]
Для Tayra Kornelias первые 3 паблика ВК и в программе отличаются
Bipartite:
![image](https://user-images.githubusercontent.com/42893404/87157127-6c080700-c2c6-11ea-8791-c9a3f168338b.png)
VK:
![image](https://user-images.githubusercontent.com/42893404/87157225-98bc1e80-c2c6-11ea-9a89-92678190d61c.png)

**Comment by nechepurenkoN** [comment]
Довольно странно, это связано с ответом API. Много ли времени прошло с момента изменения списка пабликов? Можно ли это считать временным люфтом обновлением ответа сервера?

**Comment by sandman595** [comment]
Если не ошибаюсь, до этого паблики довольно долго не менялись. Думаю, всё же можно списать на ошибки VK API
