### ISSUE TITLE
Не работает кнопка Draw

### ISSUE THREAD

**Issue by sandman595** [nechepurenkoN/spbetu2020_summer_practice#8]
По нажатии на Step всё отрисовывается, на Draw ноль реакции

**Comment by sandman595** [comment]
Ещё миниатюра аватарки берётся всегда по центру изображения, а не так, как указывал пользователь, но это не критично

**Comment by nechepurenkoN** [comment]
Кнопка draw была удалена в #11. С миниатюрой так и не смог решить проблему с API. У ключа есть необходимые модификаторы доступа, но он всё равно возвращает null, поэтому пока так. Может быть в дальнейшем это будет исправлено :)
