### ISSUE TITLE
Возможные утечки памяти

### ISSUE THREAD

**Issue by sandman595** [nechepurenkoN/spbetu2020_summer_practice#9]
Памяти занято после одного запуска визуализации:
![image](https://user-images.githubusercontent.com/42893404/87158631-b68a8300-c2c8-11ea-9aaa-9b3fdb4964b6.png)
После второго:
![image](https://user-images.githubusercontent.com/42893404/87158761-ee91c600-c2c8-11ea-8055-35c16c73b2e0.png)

**Comment by nechepurenkoN** [comment]
Вероятно, garbage collector просто ещё был вызван.

**Comment by nechepurenkoN** [comment]
Время лечит.
